FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .

RUN dotnet restore "HotelAplication/HotelAplication.csproj"
RUN dotnet build "HotelAplication/HotelAplication.csproj" -c Release -o /app/build
RUN dotnet publish "HotelAplication/HotelAplication.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "HotelAplication.dll"]
